### ISSUE TITLE
Update quarkus 2.4.2.Final  → graphql error

### ISSUE THREAD

**Issue by blackgwe** [dvddhln/quarkus-reactive-hibernate-graphql-crud#1]
After update quarkus to `2.4.2.Final` I get the following error – any idea how to fix this? Using quarkus `2.0.2.Final` everything is OK.

```
query allMovies {
  allMovies {
    title
    actors {
      name
    }
  }
}
```
**error**

```

2021-11-16 ERROR [io.sma.graphql] (executor-thread-1) SRGQL012000: Data Fetching Error: java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread: 'vert.x-eventloop-thread-12' current Thread: 'executor-thread-1'
	at org.hibernate.reactive.common.InternalStateAssertions.assertCurrentThreadMatches(InternalStateAssertions.java:46)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.threadCheck(ReactiveSessionImpl.java:154)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.checkOpen(ReactiveSessionImpl.java:1556)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.buildReactiveQueryFromName(ReactiveSessionImpl.java:474)
	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.createReactiveNamedQuery(ReactiveSessionImpl.java:465)
	at org.hibernate.reactive.mutiny.impl.MutinySessionImpl.createNamedQuery(MutinySessionImpl.java:252)
```

**Comment by dvddhln** [comment]
Did you manage to fix this with later versions?

**Comment by blackgwe** [comment]
I just tried with Quarkus v2.6.3 (see attached pom.xml) and I get the same error message.
[pom.xml.gz](https://github.com/dvddhln/quarkus-reactive-hibernate-graphql-crud/files/7963664/pom.xml.gz)

maybe 
* https://github.com/quarkusio/quarkus/issues/21111
* https://github.com/quarkusio/quarkus/issues/21433

**Comment by phillip-kruger** [comment]
Please re-test with the upcoming 2.10 release. Let me know if there are any issues
